version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 8087:8087
    volumes:
      - ./application.properties:/app/config/application.properties
